### ISSUE TITLE
code help

### ISSUE THREAD

**Issue by JXH-SHU** [littlewhitesea/STDAN#1]
Excellent work. I try to reproduce this work on CUDA11, but the code doesn't work properly.
![微信图片_20230329190223](https://user-images.githubusercontent.com/45163941/228513959-17e1c44a-5278-45eb-8218-27788a3d19e1.png)

It seems a problem about the version of CUDA.
Hope you can help me to solve my problem. Thanks.

**Comment by littlewhitesea** [comment]
Thank you for your interest in our work.

To run our code, you need to install the required packages and compile the deformable attention and convolution successfully.

Currently, you are using CUDA11, but you didn't tell the versions of torch and torchvision. The versions of recommended torch and torchvision are 1.8.0 and 0.9.0, respectively. If this kind of setting doesn't work, you can try them on CUDA10.1.

**Comment by JXH-SHU** [comment]
If I want to use the DCN in zooming, what changes do I need to make?

**Comment by littlewhitesea** [comment]
Hi, as what we have indicated, we used the different implementations of Deformable Convolution v2 from Zooming-Slow-Mo.

If you want to use the DCN in Zooming-Slow-Mo for achieving deformable attention, you can refer to the files in [src](https://github.com/littlewhitesea/STDAN/tree/main/codes/models/modules/DCNv2_latest/src) of our project and add the code of deformable attention in [src](https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/tree/master/codes/models/modules/DCNv2/src) folder of Zooming-Slow-Mo.
