### ISSUE TITLE
Experiment setup and time

### ISSUE THREAD

**Issue by fzuqxt** [littlewhitesea/STDAN#2]
Hello author, your work is very good, I would like to ask you how much is your specific experimental setting, it will probably take a few days of training to converge？

**Comment by littlewhitesea** [comment]
Thank you for your interest.

I think you can find the specific settings in the **Implementation Details** part in our paper. As for the values of other parameters, you can find them in the [yaml file](https://github.com/littlewhitesea/STDAN/blob/main/codes/options/train/train_stdan.yml).

According to the yaml file, the total number of iterations are 600000, so the required time depends on your GPU version. If you also use 1080Ti, I roughly rememberd that it requires more than 10 days.

**Comment by fzuqxt** [comment]
Thank you for your reply. I'm sorry that I haven't seen your complete paper. If I have enough video memory, does increasing batchsize mean that the number of iterations can be reduced

**Comment by fzuqxt** [comment]
Thank you for your reply. I'm sorry that I haven't seen your complete paper. If I have enough Gpu memory, does increasing batchsize mean that the number of iterations can be reduced

**Comment by littlewhitesea** [comment]
You can try it. Usually, increasing batchsize can reduce the number of iterations.

**Comment by fzuqxt** [comment]
Have you tried running on the 3090 and what are the torch and cuda versions you need

**Comment by littlewhitesea** [comment]
Hi, I don't remember clearly the versions of torch and cuda on the 3090 and I cannot have access to the computational resources in my previous lab now. 

You can attempt to install cuda 11.1, pytroch 1.8.0, and torchvision 0.9.0 using conda with the corresponding command line [here](https://pytorch.org/get-started/previous-versions/). If it doesn't work, you can try other versions. Actually, as long as the deformable attention and convolution parts could be complied successfully, our code could work on different GPU versions.
